// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jemkiomfmxtintrfeiyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbWtpb21mbXh0aW50cmZlaXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNzQ5NzIsImV4cCI6MjA1Mzc1MDk3Mn0.NGEXgIsUvckTesS-w40A8PuovWU-TqJstjMXJ9LG71I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);